<?xml version = "1.0"?>
<!DOCTYPE exec_queries [
<!ELEMENT exec_queries (exec_query*)>
<!ELEMENT exec_query (path, comment, imports, code)>
<!ATTLIST exec_query type CDATA #REQUIRED>
<!ATTLIST exec_query safe CDATA #REQUIRED>
<!ELEMENT path (dir+)>
<!ELEMENT dir (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT imports (import*)>
<!ELEMENT import (#PCDATA)>
<!ELEMENT code (#PCDATA)>
]>

<exec_queries>
    <exec_query type="SQL" safe="0">
        <path>
            <dir>SQL</dir>
        </path>
        <comment>SQL Query</comment>
        <imports></imports>
        <code>
            $conn = mysql_connect('localhost', 'mysql_user', 'mysql_password'); // Connection to the database (address, user, password)
            mysql_select_db('dbname') ;
            echo "query : ". $query ."&lt;br />&lt;br />" ;

            $res = mysql_query($query); //execution

            while($data =mysql_fetch_array($res)){
            print_r($data) ;
            echo "&lt;br />" ;
            }
            mysql_close($conn);
        </code>
    </exec_query>

</exec_queries>
