<?xml version = "1.0"?>
<!DOCTYPE template [
<!ELEMENT template (file_extension, comment, variables, imports, code)>
<!ATTLIST template type CDATA #REQUIRED>
<!ATTLIST template name CDATA #REQUIRED>
<!ELEMENT file_extension (#PCDATA)>
<!ELEMENT comment (open, close, inline)>
<!ELEMENT open (#PCDATA)>
<!ELEMENT close (#PCDATA)>
<!ELEMENT inline (#PCDATA)>
<!ELEMENT variables (variable+)>
<!ATTLIST variables prefix CDATA #REQUIRED>
<!ELEMENT variable EMPTY>
<!ATTLIST variable type CDATA #REQUIRED>
<!ATTLIST variable code CDATA #REQUIRED>
<!ATTLIST variable init CDATA #REQUIRED>
<!ELEMENT imports (import*)>
<!ELEMENT import (#PCDATA)>
<!ELEMENT code (#PCDATA)>
]>
<template type="class" name="PHP">
    <file_extension>php</file_extension>
    <comment>
        <open>/*</open>
        <close>*/</close>
        <inline>//</inline>
    </comment>
    <variables prefix="$">
        <variable type="int" code="" init="0"/>
        <variable type="string" code="" init="null"/>
    </variables>
    <imports>
    </imports>
    <code>
        &lt;?php
        /*
        {{comments}}
        */

        /*
        {{license}}
        */
        {{stdlib_imports}}
        {{other_imports}}
        {{classes}}

        {{local_var}}
        {{input_content}}
        {{filtering_content}}
        {{flaw}}
        {{sink_content}}
        {{exec_queries_content}}

        {{static_methods_calls}}
        {{other_classes_calls}}

        {{static_methods}}

        ?>
        </code>
</template>
