<?xml version="1.0"?>
<!DOCTYPE sink [
<!ELEMENT sink (sample+)>
<!ELEMENT sample (flaw_type, path, comment, imports, codes, safety, input_type, exec_type, options?)>
<!ELEMENT path (dir+)>
<!ELEMENT dir (#PCDATA)>
<!ELEMENT flaw_type (#PCDATA)>
<!ATTLIST flaw_type flaw_group CDATA #REQUIRED>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT imports (import*)>
<!ELEMENT import (#PCDATA)>
<!ELEMENT codes (code+)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT safety EMPTY>
<!ATTLIST safety safe CDATA #REQUIRED>
<!ATTLIST safety unsafe CDATA #REQUIRED>
<!ELEMENT input_type (#PCDATA)>
<!ELEMENT exec_type (#PCDATA)>
<!ELEMENT options EMPTY>
<!ATTLIST options need_complexity CDATA #IMPLIED>
]>
<sink>


  <sample>
<flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>select_from</dir>
      <dir>concatenation_simple_quote</dir>
    </path>
    <comment>construction : concatenation with simple quote</comment>
  <imports></imports>
          <code>$query = "SELECT * FROM '". {{in_var_name}} . "'";</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>select_from</dir>
      <dir>interpretation_simple_quote</dir>
    </path>
    <comment>construction : interpretation with simple quote</comment>
  <imports></imports>
          <code>$query = "SELECT * FROM ' {{in_var_name}} '";</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>select_from</dir>
      <dir>sprintf_%s_simple_quote</dir>
    </path>
    <comment>construction : use of sprintf via a %s with simple quote</comment>
  <imports></imports>
          <code>$query = sprintf("SELECT * FROM '%s'", {{in_var_name}});</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>select_from_where</dir>
      <dir>concatenation</dir>
    </path>
    <comment>construction : concatenation</comment>
  <imports></imports>
          <code>$query = "SELECT * FROM student where id=". {{in_var_name}} . "";</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>select_from_where</dir>
      <dir>concatenation_simple_quote</dir>
    </path>
    <comment>construction : concatenation with simple quote</comment>
  <imports></imports>
          <code>$query = "SELECT * FROM student where id='". {{in_var_name}} . "'";</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>select_from_where</dir>
      <dir>interpretation</dir>
    </path>
    <comment>construction : interpretation</comment>
  <imports></imports>
          <code>$query = "SELECT * FROM student where id= {{in_var_name}} ";</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>select_from_where</dir> <!-- Injection -->
      <dir>interpretation_simple_quote</dir> <!-- Injection -->
    </path>
    <comment>construction : interpretation with simple quote</comment>
  <imports></imports>
          <code>$query = "SELECT * FROM student where id=' {{in_var_name}} '";</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>select_from_where</dir>
      <dir>sprintf_%d</dir>
    </path>
    <comment>construction : use of sprintf via a %d</comment>
  <imports></imports>
          <code>$query = sprintf("SELECT * FROM student where id=%d", {{in_var_name}});</code>
        <safety safe="1" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>select_from_where</dir>
      <dir>sprintf_%d_simple_quote</dir>
    </path>
    <comment>construction : use of sprintf via a %d with simple quote</comment>
  <imports></imports>
          <code>$query = sprintf("SELECT * FROM student where id='%d'", {{in_var_name}});</code>
        <safety safe="1" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>select_from_where</dir>
      <dir>sprintf_%s_simple_quote</dir>
    </path>
    <comment>construction : use of sprintf via a %s with simple quote</comment>
  <imports></imports>
          <code>$query = sprintf("SELECT * FROM student where id='%s'", {{in_var_name}});</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>select_from_where</dir>
      <dir>sprintf_%u</dir>
    </path>
    <comment>construction : use of sprintf via a %u</comment>
  <imports></imports>
          <code>$query = sprintf("SELECT * FROM student where id=%u", {{in_var_name}});</code>
        <safety safe="1" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>select_from_where</dir>
      <dir>sprintf_%u_simple_quote</dir>
    </path>
    <comment>construction : use of sprintf via a %u with simple quote</comment>
  <imports></imports>
          <code>$query = sprintf("SELECT * FROM student where id='%u'", {{in_var_name}});</code>
        <safety safe="1" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>multiple_select</dir>
      <dir>concatenation</dir>
    </path>
    <comment>construction : concatenation</comment>
  <imports></imports>
          <code>$query = "SELECT * FROM COURSE c WHERE c.id IN (SELECT idcourse FROM REGISTRATION WHERE idstudent=". {{in_var_name}} . ")";</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>multiple_select</dir>
      <dir>concatenation_simple_quote</dir>
    </path>
    <comment>construction : concatenation with simple quote</comment>
  <imports></imports>
          <code>$query = "SELECT * FROM COURSE c WHERE c.id IN (SELECT idcourse FROM REGISTRATION WHERE idstudent='". {{in_var_name}} . "')";</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>multiple_select</dir>
      <dir>interpretation</dir>
    </path>
    <comment>construction : interpretation</comment>
  <imports></imports>
          <code>$query = "SELECT * FROM COURSE c WHERE c.id IN (SELECT idcourse FROM REGISTRATION WHERE idstudent= {{in_var_name}} )";</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>multiple_select</dir>
      <dir>interpretation_simple_quote</dir>
    </path>
    <comment>construction : interpretation with simple quote</comment>
  <imports></imports>
          <code>$query = "SELECT * FROM COURSE c WHERE c.id IN (SELECT idcourse FROM REGISTRATION WHERE idstudent=' {{in_var_name}} ')";</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>multiple_select</dir>
      <dir>sprintf_%d</dir>
    </path>
    <comment>construction : use of sprintf via a %d</comment>
  <imports></imports>
          <code>$query = sprintf("SELECT * FROM COURSE c WHERE c.id IN (SELECT idcourse FROM REGISTRATION WHERE idstudent=%d)", {{in_var_name}});</code>
        <safety safe="1" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>multiple_select</dir>
      <dir>sprintf_%d_simple_quote</dir>
    </path>
    <comment>construction : use of sprintf via a %d with simple quote</comment>
  <imports></imports>
          <code>$query = sprintf("SELECT * FROM COURSE c WHERE c.id IN (SELECT idcourse FROM REGISTRATION WHERE idstudent='%d')", {{in_var_name}});</code>
        <safety safe="1" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>multiple_select</dir>
      <dir>sprintf_%s_simple_quote</dir>
    </path>
    <comment>construction : use of sprintf via a %s with simple quote</comment>
  <imports></imports>
          <code>$query = sprintf("SELECT * FROM COURSE c WHERE c.id IN (SELECT idcourse FROM REGISTRATION WHERE idstudent='%s')", {{in_var_name}});</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>multiple_select</dir>
      <dir>sprintf_%u</dir>
    </path>
    <comment>construction : use of sprintf via a %u</comment>
  <imports></imports>
          <code>$query = sprintf("SELECT * FROM COURSE c WHERE c.id IN (SELECT idcourse FROM REGISTRATION WHERE idstudent=%u)", {{in_var_name}});</code>
        <safety safe="1" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>multiple_select</dir>
      <dir>sprintf_%u_simple_quote</dir>
    </path>
    <comment>construction : use of sprintf via a %u with simple quote</comment>
  <imports></imports>
          <code>$query = sprintf("SELECT * FROM COURSE c WHERE c.id IN (SELECT idcourse FROM REGISTRATION WHERE idstudent='%u')", {{in_var_name}});</code>
        <safety safe="1" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>


  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>join</dir>
      <dir>concatenation_simple_quote</dir>
    </path>
    <comment>construction : concatenation with simple quote</comment>
  <imports></imports>
          <code>$query = "SELECT lastname, firstname FROM drivers, vehicles WHERE drivers.id = vehicles.ownerid AND vehicles.tag='". {{in_var_name}} . "'";</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>join</dir>
      <dir>interpretation_simple_quote</dir>
    </path>
    <comment>construction : interpretation with simple quote</comment>
  <imports></imports>
          <code>$query = "SELECT lastname, firstname FROM drivers, vehicles WHERE drivers.id = vehicles.ownerid AND vehicles.tag=' {{in_var_name}} '";</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

  <sample>
    <flaw_type flaw_group="INJECTION">CWE_89</flaw_type>
    <path>
      <dir>join</dir>
      <dir>sprintf_%s_simple_quote</dir>
    </path>
    <comment>construction : use of sprintf via a %s with simple quote</comment>
  <imports></imports>
          <code>$query = sprintf("SELECT lastname, firstname FROM drivers, vehicles WHERE drivers.id = vehicles.ownerid AND vehicles.tag='%s'", {{in_var_name}});</code>
        <safety safe="0" unsafe="0"/>
    <input_type>string</input_type>
    <exec_type>SQL</exec_type>
  </sample>

</sink>
