=== stivalet/C--Vulnerability-test-suite/c_sharp_vuln_test_suite_gen/templates/dtd/file_template.dtd
<!ELEMENT template (file_extension, comment, namespace?, variables, imports, code)>
<!ATTLIST template name CDATA #REQUIRED>
<!ELEMENT file_extension (#PCDATA)>
<!ELEMENT comment (open, close, inline)>
<!ELEMENT open (#PCDATA)>
<!ELEMENT close (#PCDATA)>
<!ELEMENT inline (#PCDATA)>
<!ELEMENT namespace (#PCDATA)>
<!ELEMENT variables (variable+)>
<!ATTLIST variables prefix CDATA #REQUIRED>
<!ATTLIST variables import_code CDATA #REQUIRED>
<!ELEMENT variable EMPTY>
<!ATTLIST variable type CDATA #REQUIRED>
<!ATTLIST variable code CDATA #REQUIRED>
<!ATTLIST variable init CDATA #REQUIRED>
<!ELEMENT imports (import*)>
<!ELEMENT import (#PCDATA)>
<!ELEMENT code (#PCDATA)>

=== stivalet/C--Vulnerability-test-suite/c_sharp_vuln_test_suite_gen/templates/cs/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">

<template type="class" name="Csharp">
    <file_extension>cs</file_extension>
    <comment>
        <open>/*</open>
        <close>*/</close>
        <inline>//</inline>
    </comment>
    <variables prefix="" import_code="using {{import_file}};">
        <variable type="int" code="int" init="0"/>
        <variable type="string" code="string" init="null"/>
    </variables>
    <imports>
        <import>System</import>
    </imports>
    <code>
        /*
        {{comments}}
        */

        /*
        {{license}}
        */
        {{stdlib_imports}}
        {{other_imports}}
        namespace {{namespace_name}}{
            {{classes}}
            class {{main_name}}{
                public static void Main(string[] args){
                    {{local_var}}
                    {{input_content}}
                    {{filtering_content}}
                    {{flaw}}
                    {{sink_content}}
                    {{exec_queries_content}}
                    {{static_methods_calls}}
                    {{other_classes_calls}}
                }
                {{static_methods}}
            }
        }
        </code>
</template>
