=== stivalet/C--Vulnerability-test-suite/c_sharp_vuln_test_suite_gen/templates/dtd/sink.dtd
<!ELEMENT sink (sample+)>
<!ELEMENT sample (path, flaw_type, comment, imports, code, safety, input_type, exec_type, options?)>
<!ELEMENT path (dir+)>
<!ELEMENT dir (#PCDATA)>
<!ELEMENT flaw_type (#PCDATA)>
<!ATTLIST flaw_type flaw_group CDATA #REQUIRED>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT imports (import*)>
<!ELEMENT import (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT safety EMPTY>
<!ATTLIST safety safe CDATA #REQUIRED>
<!ATTLIST safety unsafe CDATA #REQUIRED>
<!ELEMENT input_type (#PCDATA)>
<!ELEMENT exec_type (#PCDATA)>
<!ELEMENT options EMPTY>
<!ATTLIST options need_complexity CDATA #IMPLIED>

=== stivalet/C--Vulnerability-test-suite/c_sharp_vuln_test_suite_gen/templates/cs/sink.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE sink SYSTEM "../dtd/sink.dtd">
    <sink>
        <!--
        <sample>
            <path>
                <dir></dir>
            </path>
            <flaw_type flaw_group=""></flaw_type>
            <comment></comment>
            <imports>
                <import></import>
            </imports>
            <code></code>
            <safety safe="" unsafe=""/>
            <input_type></input_type>
            <exec_type></exec_type>
        </sample>
        -->

        <sample>
            <path>
                <dir>file_exists</dir>
            </path>
            <flaw_type flaw_group="A4">CWE_22</flaw_type>
            <comment>sink : check if a file exists</comment>
            <imports>
                <import>System.IO</import>
            </imports>
            <code>
                File.Exists({{in_var_name}});
            </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>none</exec_type>
        </sample>

        <sample>
            <path>
                <dir>select_from</dir>
                <dir>concatenation_simple_quote</dir>
            </path>
            <flaw_type flaw_group="A1">CWE_89</flaw_type>
            <comment>construction : concatenation with simple quote</comment>
            <imports></imports>
            <code>
                string query = "SELECT * FROM '" + {{in_var_name}} + "'";
            </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>SQL</exec_type>
        </sample>

        <sample>
            <path>
                <dir>ls</dir>
            </path>
            <flaw_type flaw_group="A1">CWE_78</flaw_type>
            <comment>sink : run ls in a dir</comment>
            <imports>
                <import>System.IO</import>
            </imports>
            <code>
                System.Diagnostics.Process.Start("/bin/bash", "-c 'ls " + {{in_var_name}} + "'");
            </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>none</exec_type>
        </sample>

        <sample>
            <path>
                <dir>md5</dir>
            </path>
            <flaw_type flaw_group="A6">CWE_327</flaw_type>
            <comment>sink : md5 function</comment>
            <imports>
                <import>System</import>
                <import>System.Security.Cryptography</import>
                <import>System.Text</import>
            </imports>
            <code>
                using (MD5 md5Hash = MD5.Create())
                {
                    byte[] data = md5Hash.ComputeHash(Encoding.UTF8.GetBytes({{in_var_name}}));

                    // Create a new Stringbuilder to collect the bytes
                    // and create a string.
                    StringBuilder sBuilder = new StringBuilder();

                    // Loop through each byte of the hashed data
                    // and format each one as a hexadecimal string.
                    for (int i = 0; i &lt; data.Length; i++)
                    {
                        sBuilder.Append(data[i].ToString("x2"));
                    }

                    string hash = sBuilder.ToString();
                }
            </code>
            <safety safe="0" unsafe="1"/>
            <input_type>string</input_type>
            <exec_type>none</exec_type>
            <options need_complexity="0"/>
        </sample>

        <sample>
            <path>
                <dir>SQL</dir>
                <dir>Injection</dir>
            </path>
            <flaw_type flaw_group="A1">CWE_89</flaw_type>
            <comment>sink : SQL query</comment>
            <imports></imports>
            <code>
                string query = "SELECT * FROM Articles WHERE id="+{{in_var_name}};
            </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>SQL</exec_type>
        </sample>

        <sample>
            <path>
                <dir>SQL_prepared</dir>
            </path>
            <flaw_type flaw_group="A1">CWE_89</flaw_type>
            <comment>sink : SQL query</comment>
            <imports></imports>
            <code>
                string query = "SELECT * FROM Articles WHERE id=@placeholder";
                string checked_data = {{in_var_name}};
            </code>
            <safety safe="1" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>SQL_prepared</exec_type>
        </sample>

        <sample>
            <path>
                <dir>ldap</dir>
            </path>
            <flaw_type flaw_group="A1">CWE_90</flaw_type>
            <comment>sink : LDAP Query</comment>
            <imports></imports>
            <code>
                string query = "(&amp;(objectClass=person)(sn=" + {{ in_var_name }} + "))";
            </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>LDAP</exec_type>
        </sample>

        <sample>
            <path>
                <dir>XPATH</dir>
            </path>
            <flaw_type flaw_group="A1">CWE_91</flaw_type>
            <comment>sink : XPATH Query</comment>
            <imports></imports>
            <code>
                string query = "//user[@name='" + {{ in_var_name }} + "']";
            </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>XPATH</exec_type>
        </sample>

        <sample>
            <path>
                <dir>XPATH_string_format</dir>
            </path>
            <flaw_type flaw_group="A1">CWE_91</flaw_type>
            <comment>sink : XPATH Query</comment>
            <imports></imports>
            <code>
                string query = string.Format("//user[@name='{0}']",{{in_var_name}});
            </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>XPATH</exec_type>
        </sample>

        <sample>
            <path>
                <dir>XPATH_prepared</dir>
            </path>
            <flaw_type flaw_group="A1">CWE_91</flaw_type>
            <comment>sink : XPATH prepared</comment>
            <imports></imports>
            <code>
                string query = {{in_var_name}};
            </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>XPATH_prepared</exec_type>
        </sample>

        <sample>
            <path>
                <dir>null_pointer</dir>
            </path>
            <flaw_type flaw_group="A9">CWE_476</flaw_type>
            <comment>sink : NULL Pointer Dereference</comment>
            <imports></imports>
            <code>
                string cmd = null;
                cmd = Environment.GetEnvironmentVariable("cmd");
                cmd = cmd.Trim();
            </code>
            <safety safe="0" unsafe="1"/>
            <input_type>none</input_type>
            <exec_type>none</exec_type>
        </sample>

        <sample>
            <path>
                <dir>password_from_file</dir>
            </path>
            <flaw_type flaw_group="A2">CWE_256</flaw_type>
            <comment>sink : connection to a database using hardcoded password in a file</comment>
            <imports>
                <import>System</import>
                <import>System.Reflection</import>
                <import>System.Collections.Generic</import>
                <import>System.IO</import>
                <import>System.Linq</import>
                <import>MySql.Data.MySqlClient</import>
            </imports>
            <code>
                var data = new Dictionary&lt;string, string&gt;();
                foreach (var row in File.ReadAllLines("./config.properties"))
                    data.Add(row.Split('=')[0], string.Join("=",row.Split('=').Skip(1).ToArray()));

                Console.WriteLine(data["username"]);
                Console.WriteLine(data["password"]);
                string connectionString = @"server=localhost;uid=" + data["username"] + ";password=" + data["password"] + ";database=dbname";
                MySqlConnection dbConnection = null;

                try {
                    dbConnection = new MySqlConnection(connectionString);
                    dbConnection.Open();

                    dbConnection.Close();

                } catch (Exception e) {
                    Console.WriteLine(e.ToString());
                }
            </code>
            <safety safe="0" unsafe="1"/>
            <input_type>none</input_type>
            <exec_type>none</exec_type>
            <options need_complexity="0"/>
        </sample>
    </sink>
