<?xml version="1.0"?>
<!DOCTYPE input [
<!ELEMENT input (sample+)>
<!ELEMENT sample (path, comment, flaws, imports, code, input_type, output_type)>
<!ELEMENT path (dir+)>
<!ELEMENT dir (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT flaws (flaw+)>
<!ELEMENT flaw EMPTY>
<!ATTLIST flaw flaw_type CDATA #REQUIRED>
<!ATTLIST flaw safe CDATA #REQUIRED>
<!ELEMENT imports (import*)>
<!ELEMENT import (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT input_type (#PCDATA)>
<!ELEMENT output_type (#PCDATA)>
]>
    <input>
        <sample>
            <path>
                <dir>shell_commands</dir>
            </path>
            <comment>input : shell commands</comment>
            <flaws>
                <flaw flaw_type="default" safe="0"/>
            </flaws>
            <imports>
                <import>System</import>
                <import>System.IO</import>
                <import>System.Diagnostics</import>
            </imports>
            <code>
                Process process = new Process();
                process.StartInfo.FileName = "/bin/bash";
                process.StartInfo.Arguments = "-c 'cat /tmp/tainted.txt'";
                process.StartInfo.UseShellExecute = false;
                process.StartInfo.RedirectStandardOutput = true;
                process.Start();

                using(StreamReader reader = process.StandardOutput) {
                    {{out_var_name}} = reader.ReadToEnd();
                    process.WaitForExit();
                    process.Close();
                }
            </code>
            <input_type>file : /tmp/tainted.txt</input_type>
            <output_type>string</output_type>
        </sample>

        <sample>
            <path>
                <dir>readline</dir>
            </path>
            <comment>input : direct user input in string</comment>
            <flaws>
                <flaw flaw_type="default" safe="0"/>
            </flaws>
            <imports>
                <import>System</import>
            </imports>
            <code>
                {{out_var_name}} = Console.ReadLine();
            </code>
            <input_type>input : get user input in tainted</input_type>
            <output_type>string</output_type>
        </sample>

        <sample>
            <path>
                <dir>none</dir>
            </path>
            <comment>No Input</comment>
            <flaws>
                <flaw flaw_type="default" safe="1"/>
            </flaws>
            <imports>
            </imports>
            <code>
                {{out_var_name}} = "";
            </code>
            <input_type>input : no input</input_type>
            <output_type>none</output_type>
        </sample>

        <sample>
            <path>
                <dir>hardcoded_string_input</dir>
            </path>
            <comment>Hardcoded string input</comment>
            <flaws>
                <flaw flaw_type="default" safe="1"/>
            </flaws>
            <imports>
            </imports>
            <code>
                String tainted_input = "hardcoded";
            </code>
            <input_type>input : no input</input_type>
            <output_type>string</output_type>
        </sample>

        <sample>
            <path>
                <dir>hardcoded_integer_input</dir>
            </path>
            <comment>Hardcoded integer input</comment>
            <flaws>
                <flaw flaw_type="default" safe="1"/>
            </flaws>
            <imports>
            </imports>
            <code>
                int tainted_input = 0;
            </code>
            <input_type>input : no input</input_type>
            <output_type>int</output_type>
        </sample>
    </input>
